### ISSUE TITLE
Parse delay placeholderapi

### ISSUE THREAD

**Issue by SrMast3r** [joserodpt/RealMines#22]
This is realmines using 2 placeholders of your plugin
 
https://imgur.com/a/s09FJcb

It clearly shows how long it takes to load the placeholders and when reloading the hologram plugin it takes 4412 MS to load, that is too long.

https://imgur.com/a/0anFPhy
This is another mines plugin using the same placeholder of their CataMines plugin
It is clearly seen how the placeholder here works better showing dantos instantly and not taking 4444 ms to load this makes a 10ms down load.
I hope you understand
The same applies to DeluxeMenus
Clearly there is something wrong with variable declarations that use placeholdersapi

**Comment by joserodpt** [comment]
Hi there! I'm happy to report that there was indeed an issue with parsing placeholderapi placeholders. The issue was that everytime a placeholder was being requested for parse, the mine would iterate over all blocks and calculate the necessary numbers. It has been fixed in commit: https://github.com/joserodpt/RealMines/commit/2554fec86f2a5cf189fecbc6947967d6292206a2

Thanks for the report!
<img width="939" alt="image" src="https://github.com/joserodpt/RealMines/assets/18755024/78b25be6-33fd-4acb-90c7-115edb32d465">
